[package]
authors = ["Eric Trombly <etrombly@yahoo.com>"]
build = "src/build.rs"
name = "country_parser"
version = "0.1.0"

[build-dependencies]
bincode = "0.8.0"
dbf = "0.1.1"
serde = "1.0"
serde_derive = "1.0"
geo = "0.4"

[build-dependencies.shapefile-utils]
git = "https://github.com/fceschmidt/shapefile-utils"

[dependencies]
bincode = "0.8.0"
dbf = "0.1.1"
serde = "1.0"
serde_derive = "1.0"
geo = "0.4"

[dependencies.location_history]
git = "https://github.com/etrombly/location_history"
