[package]
authors = ["Eric Trombly <etrombly@yahoo.com>"]
build = "src/build.rs"
name = "country_parser"
version = "0.1.0"

[build-dependencies]
bincode = "0.8.0"
dbf = "0.1.1"
geo = "0.4.9"
serde = "1.0.11"
serde_derive = "1.0.11"

[build-dependencies.shapefile-utils]
git = "https://github.com/fceschmidt/shapefile-utils"

[dependencies]
bincode = "0.8.0"
chrono = "0.4.0"
dbf = "0.1.1"
geo = "0.4.9"
gtk = "0.1.3"
gtk-sys = "0.3.4"
relm = "0.9.6"
relm-attributes = "0.9.0"
relm-derive = "0.9.2"
serde = "1.0.11"
serde_derive = "1.0.11"

[dependencies.location_history]
git = "https://github.com/etrombly/location_history"

[profile.release]
lto = true
